spring:
  application:
    name: lynx
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
#    aof: true
#    aof-mode: everysec
#    aof-rewrite-min-size: 16
#    aof-rewrite-percentage: 1
server:
  port: 8443
  ssl:
    key-store-type: PKCS12
    key-store: classpath:server.p12
    key-store-password: changeit
    client-auth: need
    trust-store: classpath:server-truststore.p12
    trust-store-password: changeit

